service: serverless-cljs

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1

functions:
  echo:
    cljs: serverless-cljs.core/echo
    events:
      - http:
          path: echo
          method: post

plugins:
  - serverless-cljs-plugin
